# SPDX-License-Identifier: Apache-2.0
# Copyright 2024 Intel Corporation

name: Master workflow
on:
  push:
    branches:
      - master
      - GHA-integration
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./go    
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-go@v5
        with:
          go-version: '1.19'
      - name: Build
        run: go build ./...

  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-go@v5
        with:
          go-version: '1.19'
      - uses: golangci/golangci-lint-action@v3.7.0
        with:
          version: latest
          args: -v --config ./.golangci.yml --timeout=15m

  unit-tests:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./go    
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-go@v5
        with:
          go-version: '1.19'
      - name: Unit tests
        run: go test -race github.com/onosproject/onos-api/go/...

  buflint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: buflint
        env:
          BUF_VERSION: 1.8.0
        run: |
          docker run -v `pwd`:/go/src/github.com/onosproject/onos-api \
            -w /go/src/github.com/onosproject/onos-api \
            bufbuild/buf:$BUF_VERSION check lint
            
  protos:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: protos
        env:
          BUF_VERSION: v1.3.0
        run: |
          docker run \
            -v `pwd`:/onos-api \
            -w /onos-api \
            --entrypoint build/bin/compile-protos.sh \
            onosproject/protoc-go:$ONOS_PROTOC_VERSION

  license-check:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: reuse lint
        uses: fsfe/reuse-action@v2          

  fossa-check:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: FOSSA scan
        uses: fossa-contrib/fossa-action@v3
        with:
          fossa-api-key: 6d304c09a3ec097ba4517724e4a4d17d